spring:
  application:
    name: greeting
# gives a name to service (along with the EnableDiscoveryClient annotation in GreetingApplication.java), also identifies the name of the external configuration file - greeting.yml